### PR TITLE
Finalizing the package's built distribution conformed to PEP517-518

### PR DESCRIPTION
**Pull request by valizadehm**
Move *oculy* into *src*

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Nice can you just move the [build-system] section of the pyproject.toml below all the project related sections. I asked for it in #13 but missed the fact you did not do it.

**Comment by valizadehm** [comment]
> Nice can you just move the [build-system] section of the pyproject.toml below all the project related sections. I asked for it in #13 but missed the fact you did not do it.

Sorry for that! I didn't know that the order of `[build-system]` and `[project]` tables is important. As in some tutorials I saw `[build-system]` table at the top of `pyproject.toml`, I kept its positon at the top. I'll move it now.
You could cancel the current PR so that I'll make a new request with the correct finalized `pyproject.toml`.

**Comment by MatthieuDartiailh** [comment]
You can just push the additional commit to this branch.

The order is not mandatory it is just a personnal preference.

**Comment by MatthieuDartiailh** [comment]
Since you pushed the commit fixing the issue I merged the issue.

**Pull request merged**
